# Generated by Django 4.1.7 on 2023-03-11 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0005_alter_hall_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("release_date", models.DateField()),
                ("director", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("poster", models.ImageField(upload_to="poster/")),
                (
                    "imdb_ukr",
                    models.URLField(
                        help_text="Посилання на сторінку IMDB з описом фільма"
                    ),
                ),
                ("duration", models.PositiveIntegerField()),
                (
                    "start_date_right_to_rent",
                    models.DateField(help_text="Дата початку права на прокат"),
                ),
                (
                    "end_date_right_to_rent",
                    models.DateField(help_text="Дата закінчення права на прокат"),
                ),
            ],
            options={
                "verbose_name": "Фільми",
                "verbose_name_plural": "Фільм",
                "unique_together": {("title", "director")},
            },
        ),
        migrations.CreateModel(
            name="Screening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.hall"
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="screening.movie",
                    ),
                ),
            ],
        ),
    ]
