# Generated by Django 4.1.7 on 2023-03-11 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("screening", "0002_pricezone_screening_price_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screening",
            name="price_zone",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="screening.pricezone",
            ),
        ),
    ]
