# Generated by Django 4.1.7 on 2023-03-11 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_remove_seats_is_free"),
        ("screening", "0003_alter_screening_price_zone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Ціна"
                    ),
                ),
                (
                    "screening",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="screening.screening",
                        verbose_name="Сеанс",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="base.seats"
                    ),
                ),
            ],
            options={
                "verbose_name": "Квиток",
                "verbose_name_plural": "Квитки",
                "unique_together": {("screening", "seat")},
            },
        ),
    ]
