# Generated by Django 4.1.7 on 2023-03-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screening", "0004_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
