# Generated by Django 4.1.7 on 2023-03-04 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cinema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=32)),
                ("address", models.CharField(max_length=256)),
            ],
            options={"verbose_name": "Кінотеатри", "verbose_name_plural": "Кінотеатр",},
        ),
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=16)),
                (
                    "cinema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.cinema"
                    ),
                ),
            ],
            options={"verbose_name": "Зали", "verbose_name_plural": "Зал",},
        ),
        migrations.CreateModel(
            name="Raw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.hall"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ряди",
                "verbose_name_plural": "Ряд",
                "ordering": ["hall"],
            },
        ),
        migrations.CreateModel(
            name="Seats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "raw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.raw"
                    ),
                ),
            ],
            options={"verbose_name": "Місця", "verbose_name_plural": "Місце",},
        ),
    ]
