# Generated by Django 4.1.7 on 2023-03-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinema",
            name="address",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="name",
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
