# Generated by Django 4.1.7 on 2023-03-04 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_cinema_address_alter_cinema_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="raw",
            options={
                "ordering": ["number"],
                "verbose_name": "Ряди",
                "verbose_name_plural": "Ряд",
            },
        ),
        migrations.AlterUniqueTogether(
            name="raw", unique_together={("number", "hall")},
        ),
        migrations.AlterUniqueTogether(
            name="seats", unique_together={("number", "raw")},
        ),
    ]
