# Generated by Django 4.1.7 on 2023-03-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_raw_options_alter_raw_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinema", name="address", field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="name",
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name="cinema", unique_together={("name", "address")},
        ),
    ]
