# Generated by Django 4.1.7 on 2023-03-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_cinema_address_alter_cinema_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="hall", unique_together={("name", "cinema")},
        ),
    ]
