# Generated by Django 4.1.7 on 2023-03-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_seats_is_free"),
    ]

    operations = [
        migrations.RemoveField(model_name="seats", name="is_free",),
    ]
