# Generated by Django 4.1.7 on 2023-03-12 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_remove_seats_is_free"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="seats", unique_together=set(),),
        migrations.AddField(
            model_name="seats",
            name="hall",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="base.hall"
            ),
        ),
        migrations.AlterField(
            model_name="seats", name="raw", field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="seats", unique_together={("number", "raw", "hall")},
        ),
    ]
