# Generated by Django 4.1.7 on 2023-03-12 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_seats_unique_together_seats_hall_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seats",
            name="hall",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.hall"
            ),
        ),
    ]
