# Generated by Django 4.1.7 on 2023-03-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_seats_hall"),
    ]

    operations = [
        migrations.DeleteModel(name="Raw",),
    ]
